#!/bin/bash

#SBATCH --partition=long
#SBATCH --cpus-per-task=4
#SBATCH --mem=40G
#SBATCH --time=06:59:00
#SBATCH --output=./slurm_out/%j.out
#SBATCH --error=./slurm_err/%j.err

module load miniconda/3
conda activate mdcrl

export WANDB_API_KEY=1406ef3255ef2806f2ecc925a5e845e7164b5eef
wandb login

export LD_PRELOAD=/home/mila/s/sayed.mansouri-tehrani/MD-CRL/hack.so
# export WANDB_MODE=offline



# for runs more than a day, use: 1-11:59:00 (day-hour)

# ------------------------------------------------------------------------------------- #
# ------------------------------------------------------------------------------------- #
# --------------------------------- Synthetic Mixing ---------------------------------- #

# ---------------------------------- Linear Mixing ------------------------------------ #
# minmax
# python run_training.py ckpt_path=null model=mixing_synthetic model.penalty_criterion.minmax=1. model.penalty_criterion.mmd=0. datamodule=mixing datamodule.batch_size=1024 datamodule.dataset.linear=True datamodule.dataset.z_dim=8,16,32,64 datamodule.dataset.num_domains=2,4,8,16 ~callbacks.visualization_callback logger.wandb.tags=["linear-uniform","minmax"] datamodule.dataset.correlated_z=False seed=1235,4256,49685,7383,9271 --multirun
# python run_training.py ckpt_path=null model=mixing_synthetic model.penalty_criterion.minmax=1. model.penalty_criterion.mmd=0. datamodule=mixing datamodule.batch_size=1024 datamodule.dataset.linear=True datamodule.dataset.z_dim=8,16,32,64 datamodule.dataset.num_domains=2,4,8,16 ~callbacks.visualization_callback logger.wandb.tags=["linear-corr","minmax"] datamodule.dataset.correlated_z=True datamodule.dataset.corr_prob=0.5 seed=1235,4256,49685,7383,9271 --multirun
# mmd
# python run_training.py ckpt_path=null model=mixing_synthetic model.penalty_criterion.minmax=0. model.penalty_criterion.mmd=1. datamodule=mixing datamodule.batch_size=1024 datamodule.dataset.linear=True datamodule.dataset.z_dim=8,16,32,64 datamodule.dataset.num_domains=2,4,8,16 ~callbacks.visualization_callback logger.wandb.tags=["linear-uniform","mmd"] datamodule.dataset.correlated_z=False seed=1235,4256,49685,7383,9271 --multirun
# python run_training.py ckpt_path=null model=mixing_synthetic model.penalty_criterion.minmax=0. model.penalty_criterion.mmd=1. datamodule=mixing datamodule.batch_size=1024 datamodule.dataset.linear=True datamodule.dataset.z_dim=8,16,32,64 datamodule.dataset.num_domains=2,4,8,16 ~callbacks.visualization_callback logger.wandb.tags=["linear-corr","mmd"] datamodule.dataset.correlated_z=True datamodule.dataset.corr_prob=0.5 seed=1235,4256,49685,7383,9271 --multirun
# mmd + minmax
# python run_training.py ckpt_path=null model=mixing_synthetic model.penalty_criterion.minmax=1. model.penalty_criterion.mmd=1. datamodule=mixing datamodule.batch_size=1024 datamodule.dataset.linear=True datamodule.dataset.z_dim=8,16,32,64 datamodule.dataset.num_domains=2,4,8,16 ~callbacks.visualization_callback logger.wandb.tags=["linear-uniform","minmax-mmd"] datamodule.dataset.correlated_z=False seed=1235,4256,49685,7383,9271 --multirun
# python run_training.py ckpt_path=null model=mixing_synthetic model.penalty_criterion.minmax=1. model.penalty_criterion.mmd=1. datamodule=mixing datamodule.batch_size=1024 datamodule.dataset.linear=True datamodule.dataset.z_dim=8,16,32,64 datamodule.dataset.num_domains=2,4,8,16 ~callbacks.visualization_callback logger.wandb.tags=["linear-corr","minmax-mmd"] datamodule.dataset.correlated_z=True datamodule.dataset.corr_prob=0.5 seed=1235,4256,49685,7383,9271 --multirun

# ------------------------------------------------------------------------------------- #
# --------------------------------------- Balls --------------------------------------- #
# ------------------------------------------------------------------------------------- #

# ------------------------------------------------------------------------------------- #
# -------------------------- Disentanglement with encoded images ---------------------- #

# ------------------------------- iv=1,sp=1, 2 domains  ------------------------------- #
# resnet18 128 bn-enc non-overlapping dataset, uniform
# /home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_05-36-58/
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=balls_md_encoded_autoencoder model.penalty_weight=1.0 logger.wandb.tags=["balls-uniform","minmax","d2"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_05-36-58/" model.z_dim=128 model.hinge_loss_weight=0.0 model.z_dim_invariant_fraction=0.5 model/autoencoder=mlp_ae_balls ckpt_path=null model.penalty_criterion.mmd=0. model.penalty_criterion.minmax=1. model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=balls_md_encoded_autoencoder model.penalty_weight=1.0 logger.wandb.tags=["balls-uniform","mmd","d2"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_05-36-58/" model.z_dim=128 model.hinge_loss_weight=0.0 model.z_dim_invariant_fraction=0.5 model/autoencoder=mlp_ae_balls ckpt_path=null model.penalty_criterion.mmd=1. model.penalty_criterion.minmax=0. model.mmd_loss.kernel_multiplier=1.0 model.mmd_loss.kernel_number=1 model.mmd_loss.fix_sigma=1.0 model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=balls_md_encoded_autoencoder model.penalty_weight=1.0 logger.wandb.tags=["balls-uniform","minmax-mmd","d2"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_05-36-58/" model.z_dim=128 model.hinge_loss_weight=0.0 model.z_dim_invariant_fraction=0.5 model/autoencoder=mlp_ae_balls ckpt_path=null model.penalty_criterion.mmd=1. model.penalty_criterion.minmax=1. model.mmd_loss.kernel_multiplier=1.0 model.mmd_loss.kernel_number=1 model.mmd_loss.fix_sigma=1.0 model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun

# resnet18 128 bn-enc non-overlapping dataset, correlated
# /home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_07-09-43/
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=balls_md_encoded_autoencoder model.penalty_weight=1.0 logger.wandb.tags=["balls-corr","minmax","d2"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_07-09-43/" model.z_dim=128 model.hinge_loss_weight=0.0 model.z_dim_invariant_fraction=0.5 model/autoencoder=mlp_ae_balls ckpt_path=null model.penalty_criterion.mmd=0. model.penalty_criterion.minmax=1. model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=balls_md_encoded_autoencoder model.penalty_weight=1.0 logger.wandb.tags=["balls-corr","mmd","d2"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_07-09-43/" model.z_dim=128 model.hinge_loss_weight=0.0 model.z_dim_invariant_fraction=0.5 model/autoencoder=mlp_ae_balls ckpt_path=null model.penalty_criterion.mmd=1. model.penalty_criterion.minmax=0. model.mmd_loss.kernel_multiplier=1.0 model.mmd_loss.kernel_number=1 model.mmd_loss.fix_sigma=1.0 model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=balls_md_encoded_autoencoder model.penalty_weight=1.0 logger.wandb.tags=["balls-corr","minmax-mmd","d2"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_07-09-43/" model.z_dim=128 model.hinge_loss_weight=0.0 model.z_dim_invariant_fraction=0.5 model/autoencoder=mlp_ae_balls ckpt_path=null model.penalty_criterion.mmd=1. model.penalty_criterion.minmax=1. model.mmd_loss.kernel_multiplier=1.0 model.mmd_loss.kernel_number=1 model.mmd_loss.fix_sigma=1.0 model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun

# ------------------------------- iv=1,sp=1, 4 domains  ------------------------------- #
# resnet18 128 bn-enc non-overlapping dataset, uniform
# /home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_06-07-42/
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=balls_md_encoded_autoencoder model.penalty_weight=1.0 logger.wandb.tags=["balls-uniform","minmax","d4"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_06-07-42/" model.z_dim=128 model.hinge_loss_weight=0.0 model.z_dim_invariant_fraction=0.5 model/autoencoder=mlp_ae_balls ckpt_path=null model.penalty_criterion.mmd=0. model.penalty_criterion.minmax=1. model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=balls_md_encoded_autoencoder model.penalty_weight=1.0 logger.wandb.tags=["balls-uniform","mmd","d4"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_06-07-42/" model.z_dim=128 model.hinge_loss_weight=0.0 model.z_dim_invariant_fraction=0.5 model/autoencoder=mlp_ae_balls ckpt_path=null model.penalty_criterion.mmd=1. model.penalty_criterion.minmax=0. model.mmd_loss.kernel_multiplier=1.0 model.mmd_loss.kernel_number=1 model.mmd_loss.fix_sigma=1.0 model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=balls_md_encoded_autoencoder model.penalty_weight=1.0 logger.wandb.tags=["balls-uniform","minmax-mmd","d4"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_06-07-42/" model.z_dim=128 model.hinge_loss_weight=0.0 model.z_dim_invariant_fraction=0.5 model/autoencoder=mlp_ae_balls ckpt_path=null model.penalty_criterion.mmd=1. model.penalty_criterion.minmax=1. model.mmd_loss.kernel_multiplier=1.0 model.mmd_loss.kernel_number=1 model.mmd_loss.fix_sigma=1.0 model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun

# resnet18 128 bn-enc non-overlapping dataset, correlated
# /home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_07-33-56/
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=balls_md_encoded_autoencoder model.penalty_weight=1.0 logger.wandb.tags=["balls-corr","minmax","d4"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_07-33-56/" model.z_dim=128 model.hinge_loss_weight=0.0 model.z_dim_invariant_fraction=0.5 model/autoencoder=mlp_ae_balls ckpt_path=null model.penalty_criterion.mmd=0. model.penalty_criterion.minmax=1. model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=balls_md_encoded_autoencoder model.penalty_weight=1.0 logger.wandb.tags=["balls-corr","mmd","d4"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_07-33-56/" model.z_dim=128 model.hinge_loss_weight=0.0 model.z_dim_invariant_fraction=0.5 model/autoencoder=mlp_ae_balls ckpt_path=null model.penalty_criterion.mmd=1. model.penalty_criterion.minmax=0. model.mmd_loss.kernel_multiplier=1.0 model.mmd_loss.kernel_number=1 model.mmd_loss.fix_sigma=1.0 model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=balls_md_encoded_autoencoder model.penalty_weight=1.0 logger.wandb.tags=["balls-corr","minmax-mmd","d4"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_07-33-56/" model.z_dim=128 model.hinge_loss_weight=0.0 model.z_dim_invariant_fraction=0.5 model/autoencoder=mlp_ae_balls ckpt_path=null model.penalty_criterion.mmd=1. model.penalty_criterion.minmax=1. model.mmd_loss.kernel_multiplier=1.0 model.mmd_loss.kernel_number=1 model.mmd_loss.fix_sigma=1.0 model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun

# ------------------------------- iv=1,sp=1, 8 domains  ------------------------------- #
# resnet18 128 bn-enc non-overlapping dataset, uniform
# /home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_06-36-45/
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=balls_md_encoded_autoencoder model.penalty_weight=1.0 logger.wandb.tags=["balls-uniform","minmax","d8"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_06-36-45/" model.z_dim=128 model.hinge_loss_weight=0.0 model.z_dim_invariant_fraction=0.5 model/autoencoder=mlp_ae_balls ckpt_path=null model.penalty_criterion.mmd=0. model.penalty_criterion.minmax=1. model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=balls_md_encoded_autoencoder model.penalty_weight=1.0 logger.wandb.tags=["balls-uniform","mmd","d8"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_06-36-45/" model.z_dim=128 model.hinge_loss_weight=0.0 model.z_dim_invariant_fraction=0.5 model/autoencoder=mlp_ae_balls ckpt_path=null model.penalty_criterion.mmd=1. model.penalty_criterion.minmax=0. model.mmd_loss.kernel_multiplier=1.0 model.mmd_loss.kernel_number=1 model.mmd_loss.fix_sigma=1.0 model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=balls_md_encoded_autoencoder model.penalty_weight=1.0 logger.wandb.tags=["balls-uniform","minmax-mmd","d8"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_06-36-45/" model.z_dim=128 model.hinge_loss_weight=0.0 model.z_dim_invariant_fraction=0.5 model/autoencoder=mlp_ae_balls ckpt_path=null model.penalty_criterion.mmd=1. model.penalty_criterion.minmax=1. model.mmd_loss.kernel_multiplier=1.0 model.mmd_loss.kernel_number=1 model.mmd_loss.fix_sigma=1.0 model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun

# /home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_07-58-12/
# resnet18 128 bn-enc non-overlapping dataset, correlated
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=balls_md_encoded_autoencoder model.penalty_weight=1.0 logger.wandb.tags=["balls-corr","minmax","d8"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_07-58-12/" model.z_dim=128 model.hinge_loss_weight=0.0 model.z_dim_invariant_fraction=0.5 model/autoencoder=mlp_ae_balls ckpt_path=null model.penalty_criterion.mmd=0. model.penalty_criterion.minmax=1. model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=balls_md_encoded_autoencoder model.penalty_weight=1.0 logger.wandb.tags=["balls-corr","mmd","d8"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_07-58-12/" model.z_dim=128 model.hinge_loss_weight=0.0 model.z_dim_invariant_fraction=0.5 model/autoencoder=mlp_ae_balls ckpt_path=null model.penalty_criterion.mmd=1. model.penalty_criterion.minmax=0. model.mmd_loss.kernel_multiplier=1.0 model.mmd_loss.kernel_number=1 model.mmd_loss.fix_sigma=1.0 model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=balls_md_encoded_autoencoder model.penalty_weight=1.0 logger.wandb.tags=["balls-corr","minmax-mmd","d8"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_07-58-12/" model.z_dim=128 model.hinge_loss_weight=0.0 model.z_dim_invariant_fraction=0.5 model/autoencoder=mlp_ae_balls ckpt_path=null model.penalty_criterion.mmd=1. model.penalty_criterion.minmax=1. model.mmd_loss.kernel_multiplier=1.0 model.mmd_loss.kernel_number=1 model.mmd_loss.fix_sigma=1.0 model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun

# ------------------------------- iv=1,sp=1, 16 domains ------------------------------- #

# resnet18 128 bn-enc non-overlapping dataset, uniform
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=balls_md_encoded_autoencoder model.penalty_weight=1.0 logger.wandb.tags=["balls-uniform","minmax"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-05_07-21-05/" model.z_dim=128 model.hinge_loss_weight=0.0 model.z_dim_invariant_fraction=0.5 model/autoencoder=mlp_ae_balls ckpt_path=null model.penalty_criterion.mmd=0. model.penalty_criterion.minmax=1. model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=balls_md_encoded_autoencoder model.penalty_weight=1.0 logger.wandb.tags=["balls-uniform","mmd"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-05_07-21-05/" model.z_dim=128 model.hinge_loss_weight=0.0 model.z_dim_invariant_fraction=0.5 model/autoencoder=mlp_ae_balls ckpt_path=null model.penalty_criterion.mmd=1. model.penalty_criterion.minmax=0. model.mmd_loss.kernel_multiplier=1.0 model.mmd_loss.kernel_number=1 model.mmd_loss.fix_sigma=1.0 model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=balls_md_encoded_autoencoder model.penalty_weight=1.0 logger.wandb.tags=["balls-uniform","minmax-mmd"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-05_07-21-05/" model.z_dim=128 model.hinge_loss_weight=0.0 model.z_dim_invariant_fraction=0.5 model/autoencoder=mlp_ae_balls ckpt_path=null model.penalty_criterion.mmd=1. model.penalty_criterion.minmax=1. model.mmd_loss.kernel_multiplier=1.0 model.mmd_loss.kernel_number=1 model.mmd_loss.fix_sigma=1.0 model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun

# resnet18 128 bn-enc non-overlapping dataset, correlated
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=balls_md_encoded_autoencoder model.penalty_weight=1.0 logger.wandb.tags=["balls-corr","minmax"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-09_07-31-12/" model.z_dim=128 model.hinge_loss_weight=0.0 model.z_dim_invariant_fraction=0.5 model/autoencoder=mlp_ae_balls ckpt_path=null model.penalty_criterion.mmd=0. model.penalty_criterion.minmax=1. model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=balls_md_encoded_autoencoder model.penalty_weight=1.0 logger.wandb.tags=["balls-corr","mmd"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-09_07-31-12/" model.z_dim=128 model.hinge_loss_weight=0.0 model.z_dim_invariant_fraction=0.5 model/autoencoder=mlp_ae_balls ckpt_path=null model.penalty_criterion.mmd=1. model.penalty_criterion.minmax=0. model.mmd_loss.kernel_multiplier=1.0 model.mmd_loss.kernel_number=1 model.mmd_loss.fix_sigma=1.0 model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=balls_md_encoded_autoencoder model.penalty_weight=1.0 logger.wandb.tags=["balls-corr","minmax-mmd"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-09_07-31-12/" model.z_dim=128 model.hinge_loss_weight=0.0 model.z_dim_invariant_fraction=0.5 model/autoencoder=mlp_ae_balls ckpt_path=null model.penalty_criterion.mmd=1. model.penalty_criterion.minmax=1. model.mmd_loss.kernel_multiplier=1.0 model.mmd_loss.kernel_number=1 model.mmd_loss.fix_sigma=1.0 model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun


# ------------------------------------------------------------------------------------- #
# --------------------- Beta-VAE Disentanglement with encoded images ------------------ #

# ------------------------------- iv=1,sp=1, 2 domains  ------------------------------- #
# resnet18 128 bn-enc non-overlapping dataset, uniform
# /home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_05-36-58/
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=beta_vae model.beta=1.0 logger.wandb.tags=["balls-uniform-bvae","minmax","d2"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_05-36-58/" model.z_dim=128 model/autoencoder=beta_vae ckpt_path=null model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun
python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=balls_md_encoded_autoencoder model.beta=1.0 logger.wandb.tags=["test"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_05-36-58/" model.z_dim=128 ckpt_path=null model.save_encoded_data=False model/autoencoder=beta_vae
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=beta_vae model.beta=1.0 logger.wandb.tags=["balls-uniform-bvae","mmd","d2"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_05-36-58/" model.z_dim=128 model/autoencoder=beta_vae ckpt_path=null model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=beta_vae model.beta=1.0 logger.wandb.tags=["balls-uniform-bvae","minmax-mmd","d2"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_05-36-58/" model.z_dim=128 model/autoencoder=beta_vae ckpt_path=null model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun

# resnet18 128 bn-enc non-overlapping dataset, correlated
# /home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_07-09-43/
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=beta_vae model.beta=1.0 logger.wandb.tags=["balls-corr-bvae","minmax","d2"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_07-09-43/" model.z_dim=128 model/autoencoder=beta_vae ckpt_path=null model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=beta_vae model.beta=1.0 logger.wandb.tags=["balls-corr-bvae","mmd","d2"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_07-09-43/" model.z_dim=128 model/autoencoder=beta_vae ckpt_path=null model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=beta_vae model.beta=1.0 logger.wandb.tags=["balls-corr-bvae","minmax-mmd","d2"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_07-09-43/" model.z_dim=128 model/autoencoder=beta_vae ckpt_path=null model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun

# ------------------------------- iv=1,sp=1, 4 domains  ------------------------------- #
# resnet18 128 bn-enc non-overlapping dataset, uniform
# /home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_06-07-42/
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=beta_vae model.beta=1.0 logger.wandb.tags=["balls-uniform-bvae","minmax","d4"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_06-07-42/" model.z_dim=128 model/autoencoder=beta_vae ckpt_path=null model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=beta_vae model.beta=1.0 logger.wandb.tags=["balls-uniform-bvae","mmd","d4"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_06-07-42/" model.z_dim=128 model/autoencoder=beta_vae ckpt_path=null model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=beta_vae model.beta=1.0 logger.wandb.tags=["balls-uniform-bvae","minmax-mmd","d4"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_06-07-42/" model.z_dim=128 model/autoencoder=beta_vae ckpt_path=null model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun

# resnet18 128 bn-enc non-overlapping dataset, correlated
# /home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_07-33-56/
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=beta_vae model.beta=1.0 logger.wandb.tags=["balls-corr-bvae","minmax","d4"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_07-33-56/" model.z_dim=128 model/autoencoder=beta_vae ckpt_path=null model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=beta_vae model.beta=1.0 logger.wandb.tags=["balls-corr-bvae","mmd","d4"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_07-33-56/" model.z_dim=128 model/autoencoder=beta_vae ckpt_path=null model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=beta_vae model.beta=1.0 logger.wandb.tags=["balls-corr-bvae","minmax-mmd","d4"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_07-33-56/" model.z_dim=128 model/autoencoder=beta_vae ckpt_path=null model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun

# ------------------------------- iv=1,sp=1, 8 domains  ------------------------------- #
# resnet18 128 bn-enc non-overlapping dataset, uniform
# /home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_06-36-45/
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=beta_vae model.beta=1.0 logger.wandb.tags=["balls-uniform-bvae","minmax","d8"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_06-36-45/" model.z_dim=128 model/autoencoder=beta_vae ckpt_path=null model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=beta_vae model.beta=1.0 logger.wandb.tags=["balls-uniform-bvae","mmd","d8"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_06-36-45/" model.z_dim=128 model/autoencoder=beta_vae ckpt_path=null model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=beta_vae model.beta=1.0 logger.wandb.tags=["balls-uniform-bvae","minmax-mmd","d8"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_06-36-45/" model.z_dim=128 model/autoencoder=beta_vae ckpt_path=null model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun

# /home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_07-58-12/
# resnet18 128 bn-enc non-overlapping dataset, correlated
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=beta_vae model.beta=1.0 logger.wandb.tags=["balls-corr-bvae","minmax","d8"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_07-58-12/" model.z_dim=128 model/autoencoder=beta_vae ckpt_path=null model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=beta_vae model.beta=1.0 logger.wandb.tags=["balls-corr-bvae","mmd","d8"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_07-58-12/" model.z_dim=128 model/autoencoder=beta_vae ckpt_path=null model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=beta_vae model.beta=1.0 logger.wandb.tags=["balls-corr-bvae","minmax-mmd","d8"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-10_07-58-12/" model.z_dim=128 model/autoencoder=beta_vae ckpt_path=null model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun

# ------------------------------- iv=1,sp=1, 16 domains ------------------------------- #

# resnet18 128 bn-enc non-overlapping dataset, uniform
python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model=beta_vae model.beta=1.0 model.optimizer.lr=0.001 model.z_dim_invariant_data=2 datamodule=balls_encoded datamodule.batch_size=1024 logger.wandb.tags=["balls-uniform-bvae","minmax"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-05_07-21-05/" model.z_dim=128 model/autoencoder=mlp_ae_balls ckpt_path=null model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=beta_vae model.beta=1.0 logger.wandb.tags=["balls-uniform-bvae","mmd"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-05_07-21-05/" model.z_dim=128 model/autoencoder=beta_vae ckpt_path=null model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=beta_vae model.beta=1.0 logger.wandb.tags=["balls-uniform-bvae","minmax-mmd"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-05_07-21-05/" model.z_dim=128 model/autoencoder=beta_vae ckpt_path=null model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun

# resnet18 128 bn-enc non-overlapping dataset, correlated
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=beta_vae model.beta=1.0 logger.wandb.tags=["balls-corr-bvae","minmax"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-09_07-31-12/" model.z_dim=128 model/autoencoder=beta_vae ckpt_path=null model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=beta_vae model.beta=1.0 logger.wandb.tags=["balls-corr-bvae","mmd"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-09_07-31-12/" model.z_dim=128 model/autoencoder=beta_vae ckpt_path=null model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun
# python run_training.py trainer.accelerator="cpu" trainer.devices="auto" model.optimizer.lr=0.001 datamodule=balls_encoded datamodule.batch_size=1024 model=beta_vae model.beta=1.0 logger.wandb.tags=["balls-corr-bvae","minmax-mmd"] ~callbacks.early_stopping ~callbacks.visualization_callback run_path="/home/mila/s/sayed.mansouri-tehrani/scratch/logs/training/runs/autoencoder_md_balls_128_iv_1_sp_1/2023-10-09_07-31-12/" model.z_dim=128 model/autoencoder=beta_vae ckpt_path=null model.save_encoded_data=False seed=1235,4256,49685,7383,9271 --multirun


conda deactivate
module purge
