program: run_training.py
method: bayes
metric:
  goal: minimize
  name: val_loss
parameters:
  datamodule:
    batch_size:
      values: [128, 256, 512]
    dataset:
      num_domains:
        values: [2, 4, 6, 8, 10]
      z_dim:
        values: [4, 8, 16, 32, 64]
  model:
    penalty_weight:
      values: [0.01, 0.1, 1.0, 10.0]
    wait_steps:
      values: [0, 500, 2000]
    linear_steps:
      values: [1, 2000, 3000]
    optimizer:
      values: 
        [adam, adamw]
      lr:
        values: [1e-4, 1e-3, 1e-2, 1e-1]
    scheduler_config:
      values: [null, reduce_on_plateau]
  
  trainer:
    gpus:
      values: [0]
    min_epochs:
      values: [50]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}

name: amin's first wandb sweep
description: Run training for a single dataset
project: ${logger.wandb.project}

run_cap: 100
