_target_: datamodule.base_datamodule.BaseDataModule

defaults:
  - dataset: synthetic_mixing
  
dataset_name: synthetic_mixing
datamodule_name: ${datamodule.dataset.dataset_name}

save_dataset: False
load_dataset: False
data_dir: null

seed: ${seed}

transform:
    augs: [] # choices=["shift", "hflip", "vflip", "scale", "rotate"]

# Concerning the data_loaders
batch_size: 512
num_workers: 6
shuffle: False
drop_last: False

# Samples
num_samples:
    train: 10000 # 30000
    valid: 2000 # 4000
    test: 2000

   
transforms:
