_target_: models.modules.fc_ae_synthetic.FCAE

latent_dim: ${model.z_dim_invariant}

encoder_fc:
  _target_: models.modules.fc_ae_synthetic.Encoder

  encoder_layers:
    Linear1:
      _target_: torch.nn.Linear
      in_features: ${datamodule.dataset.x_dim}
      out_features: ${model.autoencoder.latent_dim}
    
decoder_fc:
  _target_: models.modules.fc_ae_synthetic.Decoder

  decoder_layers:
    Linear1:
      _target_: torch.nn.Linear
      in_features: ${model.autoencoder.latent_dim}
      out_features: ${datamodule.dataset.x_dim}